export default {
    // Api requests
    GET_ALL_ENCOUNTERS: 'GET_ALL_ENCOUNTERS',
    GET_ALL_ENCOUNTERS_BY_PATIENT_ID: 'GET_ALL_ENCOUNTERS_BY_PATIENT_ID',
    CREATE_ENCOUNTER: 'CREATE_ENCOUNTER',
    UPDATE_ENCOUNTER: 'UPDATE_ENCOUNTER',
    DELETE_ENCOUNTER: 'DELETE_ENCOUNTER',

    // Success handlers
    GET_ALL_ENCOUNTERS_SUCCESS: 'GET_ALL_ENCOUNTERS_SUCCESS',
    GET_ALL_PATIENT_ENCOUNTERS_SUCCESS: 'GET_ALL_PATIENT_ENCOUNTERS_SUCCESS',

    // Selection of encounters
    SET_SELECTED_ENCOUNTER: 'SET_SELECTED_ENCOUNTER',

    // Error handling
    SET_ENCOUNTER_ERROR: 'SET_ENCOUNTER_ERROR',
    ENCOUNTER_ERROR_RESET: 'ENCOUNTER_ERROR_RESET',
}