logging:
  level:
    root: INFO

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari.connection-timeout: 3000
    platform: postgres
    url: jdbc:postgresql://localhost:5432/finalProject
    username: postgres
    password: pass@word1
    driverClassName: org.postgresql.Driver